import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FaCalendarAlt, FaMapMarkerAlt, FaSearch, FaRegClock, FaTicketAlt, FaShieldAlt, FaArrowRight } from 'react-icons/fa';
import api from '../utils/axios';

const features = [
    { icon: FaRegClock, title: 'Fast Booking', text: 'Secure your tickets instantly with our fast streamlined booking infrastructure built for speed.' },
    { icon: FaTicketAlt, title: 'Seamless Access', text: 'Download tickets instantly or manage them right from your personal dashboard with ease.' },
    { icon: FaShieldAlt, title: 'Secure Platform', text: 'All transactions and registrations are protected by modern security and 2FA OTP technology.' },
];

const formatDate = (date) => new Date(date).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

const Home = () => {
    const [events, setEvents] = useState([]);
    const [search, setSearch] = useState('');
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const timeoutId = setTimeout(async () => {
            try {
                const { data } = await api.get(`/events?search=${encodeURIComponent(search)}`);
                setEvents(data);
            } catch (error) {
                console.error('Error fetching events:', error);
            } finally {
                setLoading(false);
            }
        }, 300);
        return () => clearTimeout(timeoutId);
    }, [search]);

    return (
        <div className="bg-[#110926] text-white">
            <section className="relative grid min-h-[590px] place-items-center overflow-hidden bg-[linear-gradient(180deg,rgba(17,9,38,.2),#110926),url('/home-bg.jpg')] bg-cover bg-center text-center after:absolute after:inset-0 after:bg-[linear-gradient(180deg,rgba(17,9,38,.18),rgba(17,9,38,.82))] max-[700px]:min-h-[330px]"><div className="relative z-[1] max-w-[650px] px-5 pb-[70px] pt-[140px] max-[700px]:pb-[35px] max-[700px]:pt-[90px]"><span className="inline-block rounded-[30px] border border-[#d200d8] px-5 py-1.5 text-[13px] font-semibold max-[700px]:px-3 max-[700px]:py-1 max-[700px]:text-[10px]">Welcome to Eventify</span><h1 className="my-[18px] text-[clamp(38px,5vw,62px)] font-extrabold uppercase leading-[1.05] max-[700px]:my-3 max-[700px]:text-[29px]">Find your next<br /><span className="text-[#d200d8]">unforgettable</span><br />experience</h1><p className="mx-auto mb-7 max-w-[590px] text-[13px] leading-[1.6] text-[#eee8f4] max-[700px]:mb-[15px] max-[700px]:text-[8px] max-[700px]:leading-[1.3]">Discover the best tech conferences, late-night music festivals, and hands-on workshops happening directly in your area. Secure your spot today.</p><label className="mx-auto flex h-[42px] max-w-[410px] items-center gap-2 rounded-[30px] border-2 border-[#d200d8] bg-white px-[15px] py-1 text-[#d200d8] max-[700px]:h-[29px] max-[700px]:max-w-[300px] max-[700px]:pl-2"><FaSearch aria-hidden="true" /><input className="min-w-0 flex-1 border-0 text-[11px] text-[#333] outline-0 max-[700px]:text-[8px]" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search for your event..." aria-label="Search for an event" /><span className="flex items-center gap-2 rounded-[20px] bg-gradient-to-r from-[#d200d8] to-[#4c0087] px-[15px] py-2 text-[11px] font-semibold text-white max-[700px]:px-2.5 max-[700px]:py-1.5 max-[700px]:text-[8px]">Explore <FaArrowRight aria-hidden="true" /></span></label></div></section>
            <section className="relative z-[2] mx-auto -mt-[25px] max-w-[1080px] rounded-[48%_48%_12%_12%/5%_5%_4%_4%] bg-[#110926] px-[30px] pb-[90px] pt-[70px] max-[700px]:-mt-3 max-[700px]:rounded-[45%_45%_8%_8%/3%_3%_2%_2%] max-[700px]:px-[13px] max-[700px]:pb-[60px] max-[700px]:pt-10" id="events"><div className="flex items-center justify-between gap-5 border-b border-white/25 pb-[13px]"><h2 className="m-0 text-[26px] font-extrabold uppercase text-[#d200d8] max-[700px]:text-base">Upcoming events</h2><span className="text-[11px] max-[700px]:text-[8px]">{events.length} results found</span></div>{loading ? <p className="py-[70px] text-center text-[#c9bdd8]">Loading events...</p> : events.length === 0 ? <p className="py-[70px] text-center text-[#c9bdd8]">No events found matching your search.</p> : <div className="mt-7 grid grid-cols-3 gap-[14px] max-[700px]:mt-[17px] max-[700px]:grid-cols-1 max-[700px]:gap-2">{events.map((event) => { const image = event.imageUrl || event.image; const availability = event.totalSeats ? Math.max(0, Math.min(100, (event.availableSeats / event.totalSeats) * 100)) : 0; return <article className="overflow-hidden rounded-[9px] border border-[#7700a0] bg-gradient-to-br from-[#4c0087]/55 to-[#1b0931]/95" key={event._id}><div className="relative h-[138px] p-1.5 max-[700px]:h-[132px]">{image ? <img src={image} alt={event.title} className="h-full w-full rounded-md object-cover" /> : <div className="grid h-full w-full place-items-center rounded-md bg-[#4c0087]">{event.category}</div>}<span className="absolute right-3 top-3 rounded-[10px] bg-[#4c0087] px-2 py-0.5 text-[9px]">{event.ticketPrice === 0 ? 'FREE' : `₹${event.ticketPrice}`}</span></div><div className="p-[5px_9px_10px]"><span className="text-[9px] uppercase">{event.category}</span><h3 className="my-[3px] mb-[9px] min-h-[34px] text-[14px] font-semibold leading-[1.1] text-[#d200d8] max-[700px]:text-[13px]">{event.title}</h3><div className="grid gap-[5px] text-[8px]"><span className="flex items-center gap-[7px]"><FaCalendarAlt className="text-[#d200d8]" />{formatDate(event.date)}</span><span className="flex items-center gap-[7px]"><FaMapMarkerAlt className="text-[#d200d8]" />{event.location}</span></div><div className="my-2 h-1.5 rounded-[5px] bg-[#59006f]"><span className="block h-full rounded-[inherit] bg-[#d200d8]" style={{ width: `${availability}%` }} /></div><small className="text-[7px]">{event.availableSeats} of {event.totalSeats} seats remaining</small><Link to={`/events/${event._id}`} className="mt-2 flex items-center justify-center gap-2 rounded-[7px] bg-[#d200d8] p-[7px] text-[11px] font-bold">View Details <FaArrowRight /></Link></div></article>; })}</div>}</section>
            <section className="bg-[linear-gradient(rgba(17,9,38,.76),rgba(17,9,38,.92)),url('/why-choose-us-bg.jpg')] bg-cover bg-center px-[30px] pb-[120px] pt-[100px] text-center max-[700px]:pb-[60px] max-[700px]:pt-[50px]"><div className="mx-auto max-w-[550px]"><h2 className="m-0 text-[26px] font-extrabold uppercase text-[#d200d8] max-[700px]:text-base">Why choose us?</h2><p className="my-3 mb-[35px] text-[12px] text-[#eee8f4] max-[700px]:text-[9px] max-[700px]:leading-[1.3]">Discover experiences worth remembering, with simple booking and thoughtful support from start to finish.</p></div><div className="mx-auto grid max-w-[800px] grid-cols-3 gap-3 max-[700px]:max-w-[220px] max-[700px]:grid-cols-1 max-[700px]:gap-2.5">{features.map(({ icon: Icon, title, text }) => <div className="min-h-[165px] rounded-[10px] border border-[#82009d] bg-[#260e3a]/65 p-[18px] max-[700px]:min-h-[145px]" key={title}><div className="mx-auto mb-3 grid h-[52px] w-[52px] place-items-center rounded-[14px] bg-gradient-to-br from-[#d200d8] to-[#4c0087] text-[26px]"><Icon /></div><h3 className="mb-[7px] text-[13px] font-semibold uppercase text-[#d200d8]">{title}</h3><p className="m-0 text-[10px] leading-[1.4]">{text}</p></div>)}</div></section>
            <footer className="mx-auto grid max-w-[1080px] grid-cols-[1fr_auto] gap-x-20 gap-y-5 px-[30px] pb-[35px] pt-[65px] max-[700px]:block max-[700px]:px-5 max-[700px]:pb-[25px] max-[700px]:pt-[45px]"><div><img src="/logo-pink.svg" alt="Eventify" className="w-[125px] max-[700px]:w-[105px]" /><p className="max-w-[330px] text-[11px] leading-[1.5] text-[#eee8f4] max-[700px]:text-[9px]">The simplest, most dynamic way to manage, discover, and host world-class events in your local city. Let&apos;s make memories together.</p></div><nav className="flex gap-7 self-center text-xs max-[700px]:my-[25px] max-[700px]:justify-between max-[700px]:gap-2.5 max-[700px]:text-[9px]"><Link to="/" className="hover:text-[#d200d8]">Home</Link><a href="#events" className="hover:text-[#d200d8]">Events</a><Link to="/login" className="hover:text-[#d200d8]">Login</Link><Link to="/register" className="hover:text-[#d200d8]">Signup</Link></nav><small className="col-span-full border-t border-white/25 pt-[22px] text-center text-[10px] text-[#c9bdd8] max-[700px]:block max-[700px]:pt-[15px] max-[700px]:text-[7px]">© {new Date().getFullYear()} Eventify Platform. All rights reserved.</small></footer>
        </div>
    );
};

export default Home;
